name: Artifact deployment

on:
  release:
    types: [created]

jobs:
  github:
    name: Github
    uses: Bernardo-MG/github-workflow-maven/.github/workflows/deploy_github.yml@v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
